version: '3'
services:
  strapi:
    image: strapi/strapi
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_NAME: data.db
      DATABASE_FILENAME: ./data/data.db
    volumes:
      - ./data:/srv/app/data
