name: Deploy Strapi App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        id: plan
        run: terraform plan -out=plan.out

      - name: Apply Terraform
        run: terraform apply -auto-approve plan.out

      - name: Get instance IP
        id: get_instance_ip
        run: echo "INSTANCE_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV

  deploy:
    name: 'Deploy Strapi'
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy Docker Compose file
        run: |
          scp -o StrictHostKeyChecking=no -i /mnt/data/Intern.pem ./docker-compose.yml ubuntu@${{ env.INSTANCE_IP }}:/home/ubuntu/docker-compose.yml

      - name: Run Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i /mnt/data/Intern.pem ubuntu@${{ env.INSTANCE_IP }} << EOF
          sudo docker-compose -f /home/ubuntu/docker-compose.yml up -d
          EOF

      - name: Verify Deployment
        run: curl http://${{ env.INSTANCE_IP }}:1337
