name: Deploy Strapi

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  deploy:
    name: 'Deploy Strapi'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Fetch Terraform Outputs
        id: fetch_outputs
        run: echo "INSTANCE_IP=${{ github.event.workflow_run.outputs.instance_ip }}" >> $GITHUB_ENV

      - name: Debug IP
        run: echo "Instance IP: ${{ env.INSTANCE_IP }}"

      - name: Check SSH connection
        run: ssh -o StrictHostKeyChecking=no -i /mnt/data/Intern.pem ubuntu@${{ env.INSTANCE_IP }} echo "SSH connection successful"

      - name: Copy Docker Compose file
        run: scp -o StrictHostKeyChecking=no -i /mnt/data/Intern.pem ./docker-compose.yml ubuntu@${{ env.INSTANCE_IP }}:/home/ubuntu/docker-compose.yml

      - name: Run Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i /mnt/data/Intern.pem ubuntu@${{ env.INSTANCE_IP }} << EOF
          sudo docker-compose -f /home/ubuntu/docker-compose.yml up -d
          EOF

      - name: Verify Deployment
        run: curl http://${{ env.INSTANCE_IP }}:1337
