name: Terraform Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        id: plan
        run: terraform plan -out=plan.out
        timeout-minutes: 10

      - name: Apply Terraform
        run: terraform apply -auto-approve plan.out
        timeout-minutes: 15

      - name: Get instance IP
        id: get_instance_ip
        run: echo "::set-output name=instance_ip::$(terraform output -raw instance_ip)"
